### ISSUE TITLE
ImportError: cannot import name 'SteemConnector'

### ISSUE THREAD

**Issue by ghost** [charlesjlee/steemBot#5]
Any suggestions?

```
2018-10-25T21:03:03.354415+00:00 app[scheduler.6475]: Traceback (most recent call last):
2018-10-25T21:03:03.354440+00:00 app[scheduler.6475]:   File "bot.py", line 9, in <module>
2018-10-25T21:03:03.354646+00:00 app[scheduler.6475]:     from piston.steem import Steem
2018-10-25T21:03:03.354649+00:00 app[scheduler.6475]:   File "/app/.heroku/python/lib/python3.6/site-packages/piston/steem.py", line 3, in <module>
2018-10-25T21:03:03.354796+00:00 app[scheduler.6475]:     from steem.steem import SteemConnector as SteemConnectorSteem
2018-10-25T21:03:03.354803+00:00 app[scheduler.6475]: ImportError: cannot import name 'SteemConnector'
```

**Comment by ghost** [comment]
If anyone else has this problem, do this:

in bot.py, update the import to:

from steem import Steem

and install with:

pip3 install piston-cli
